sonata_admin:
    title: 'Mediaplayer Admin'
    title_logo: img/media.png
    dashboard:
        blocks:
        -
            position: left
            type: sonata.admin.block.admin_list

        -
            position: right
            type: sonata.block.service.text
            settings:
                content: >
                    <h2>Bienvenue sur la page d'Admin de mediaplayer</h2>
        groups:
            Administration:
            news:
                label:  Home
                items:
                - route:        home
                  label:        Main
                - route:        logout
                  label:        Logout

    templates:
        layout:     '@SonataAdmin/standard_layout.html.twig'
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.user.block.menu:
        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.admin.block.search_result:
