sonata_admin:
    title: 'Mediaplayer Admin'
    title_logo: img/media.png
    dashboard:
        blocks:
        -
            position: left
            type: sonata.admin.block.admin_list

        -
            position: right
            type: sonata.block.service.text
            settings:
                content: >
                    <h2>Bienvenue sur MediaPlayer Admin</h2>

    templates:
        layout:     '@SonataAdmin/standard_layout.html.twig'
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.user.block.menu:
        sonata.block.service.text:
        sonata.block.service.rss:
