sonata_admin:
    title: 'Mediaplayer Admin'
    title_logo: img/media.png
    dashboard:
        blocks:
        -
            position: left
            type: sonata.admin.block.admin_list

        -
            position: right
            type: sonata.block.service.text
            settings:
                content: >
                    <h2>Welcome to the Sonata Admin</h2>
                    <p>This is a <code>sonata.block.service.text</code> from the Block
                    Bundle, you can create and add new block in these area by configuring
                    the <code>sonata_admin</code> section.</p> <br /> For instance, here
                    a RSS feed parser (<code>sonata.block.service.rss</code>):
        -
            position: right
            type: sonata.block.service.rss
            roles: [POST_READER]
            settings:
                title: Sonata Project's Feeds
                url: https://sonata-project.org/blog/archive.rss
    templates:
        layout:     '@SonataAdmin/standard_layout.html.twig'
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.user.block.menu:
        sonata.block.service.text:
        sonata.block.service.rss:
