<?php
/**
 * Created by PhpStorm.
 * User: erolland2018
 * Date: 26/11/2018
 * Time: 15:25
 */

namespace App\Admin;

use App\Entity\Genre;
use App\Entity\Utilisateur;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\ModelType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class MediaAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->with('Content', ['class' => 'col-md-9'])
                        ->add('name', TextType::class)
                        ->add('description', TextType::class)
                        ->add('dateCreated', DateTimeType::class)
                        ->add('picture',TextType::class)
                        ->add('extension',TextType::class)
                    ->end()
                    ->with('Meta data', ['class' => 'col-md-3'])
                        ->add('genre', ModelType::class, [
                            'class' => Genre::class,
                            'property' => 'name',
                             ])
                        ->add('utilisateur',ModelType::class, [
                            'class' => Utilisateur::class,
                            'property' => 'username',])
                    ->end()
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('name');
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper->addIdentifier('name')
                    ->add('description')
                    ->add('dateCreated')
                    ->add('picture')
                    ->add('extension')
                    ->add('utilisateur.username')
                    ->add('genre.name');
    }

    public function prePersist($object)
    {
        parent::prePersist($object); // TODO: Change the autogenerated stub
    }

    public function preUpdate($user)
    {
        $this->getUserManager()->updatePassword($user);
    }

    public function setUserManager(UserManagerInterface $userManager)
    {
        $this->userManager = $userManager;
    }

    /**
     * @return UserManagerInterface
     */
    public function getUserManager()
    {
        return $this->userManager;
    }

}